# SwiftLint configuration for OscDrax

# Paths to include in linting
included:
  - OscDrax

# Paths to exclude from linting
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - ${PWD}/OscDrax.xcodeproj

# Configure individual rules
disabled_rules:
  - trailing_whitespace
  - todo
  - orphaned_doc_comment

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

analyzer_rules:
  - unused_declaration
  - unused_import

# Rule configuration
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 40
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_name:
  min_length: 3
  max_length: 40
  allowed_symbols: ["_"]

identifier_name:
  min_length: 2
  max_length: 40
  allowed_symbols: ["_"]
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level: 2
  function_level: 3

force_cast: warning
force_try: warning
force_unwrapping: warning

custom_rules:
  no_print_statements:
    name: "No print statements"
    regex: '^\s*print\('
    message: "Use proper logging instead of print statements"
    severity: warning

  mark_format:
    name: "MARK Format"
    regex: '\/\/\s*MARK:[^\s]'
    message: "Add a space after MARK:"
    severity: warning

reporter: "xcode"